apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zealand-mentalshower
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http, https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - mentalshower.boti7.com
    secretName: le-zealand-mentalshower
  rules:
  - host: mentalshower.boti7.com
    http:
      paths:
      - path: /
        backend:
          serviceName: zealand-mentalshower
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: zealand-mentalshower
  namespace: apps
spec:
  selector:
    app: zealand-mentalshower
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zealand-mentalshower
  namespace: apps
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: zealand-mentalshower
  template:
    metadata:
      labels:
        app: zealand-mentalshower
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: zealand-mentalshower
        image: registry.boti7.com/apps/zealand-mentalshower
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
